name: all_about_forced_update
description: Force update an outdated app
version: 4.0.0
homepage: https://allaboutapps.at

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0
  http: ^1.2.0
  open_store: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
